import Layout from "../components/Layout";
import Head from "next/head";
// import Link from "next/link";
import Banner from "../components/Banner";
import Image from "../components/Image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
      </Head>
      <Banner></Banner>
      <div>
        <Image
          src="/images/boy-colorful-photoshoot.jpg"
          alt="Boy colorful photo"
          width="100%"
          height="calc(100vh - 65px - 3.2rem)"
          objectFit="none"
          objectPosition="right top"
        ></Image>
      </div>
    </div>

    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Link href="/ProductListing">
    //     <a>To another page</a>
    //   </Link>
    // </div>
  );
}
